apiVersion: v1
kind: Service
metadata:
  labels:
    deployment: redis
  name: redis
spec:
  ports:
    - name: redis-port
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    deployment: redis
  type: ClusterIP

